# -- The resource name suffix
nameOverride: ""
# -- The full resource name override
fullnameOverride: ""

image:
  # -- The container image to run
  repository: ghcr.io/pocket-id/pocket-id
  # -- The pull policy for images
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart version.
  tag: ""

# -- Pocket-id configuration variables
# For more information see: https://pocket-id.org/docs/configuration/environment-variables
config:
  {}
  # appUrl: ""
  # trustProxy: ""
  # maxmindLicenseKey: ""
  # puid: ""
  # dbProvider: ""
  # dbConnectionString: ""
  # uploadPath: ""
  # geoliteDbPath: ""
  # port: ""
  # host: ""

# -- Name of an existing config map containing any environment variables
existingConfigMap: ""

# -- Name of an existing secret containing any environment variables
existingSecret: ""

# -- This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 1411

ingress:
  # -- Enables an ingress for the application
  enabled: false
  className: ""
  # -- Annotations for the ingress
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  # -- Adds tls to the ingress
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Specifiy resources for the pod
resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  initialDelaySeconds: 60
  httpGet:
    # -- Healthcheck endpoint
    path: /health
    port: http
readinessProbe:
  initialDelaySeconds: 60
  httpGet:
    # -- Healthcheck endpoint
    path: /health
    port: http

persistence:
  # -- Persist data to a persistent volume
  enabled: true
  # -- A manually managed Persistent Volume and Claim
  # Requires persistence.enabled: true
  # If defined, PVC must be created manually before volume will be bound
  existingClaim: ""
  # -- Persistent Volume Storage Class
  # If defined, storageClassName: <storageClass>
  # If set to "-", storageClassName: "", which disables dynamic provisioning
  # If undefined (the default) or set to null, no storageClassName spec is
  #   set, choosing the default provisioner.  (gp2 on AWS, standard on
  #   GKE, AWS & OpenStack)
  storageClass: ""
  annotations: {}
  accessMode: ReadWriteOnce
  size: 8Gi

# -- Additional volumes on the pod definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts on the pod definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
