name: Release

on:
  push:
    branches: [main]

permissions:
  packages: write
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get Version
        id: version
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '.appVersion | sub("^v"; "")' Chart.yaml
      
      - name: Push Helm chart
        env:
          VERSION: ${{ steps.version.outputs.result }}
        run: |
          helm package . --version $VERSION --app-version v$VERSION --dependency-update
          helm push pocket-id-${VERSION}.tgz oci://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
